### ISSUE TITLE
Package descriptions should include more information

### ISSUE THREAD

**Issue by szhorvat** [paclets/PacletServer#3]
The package description pages, generated from the PacletInfo files, should include more information.

It should include the `URL`, if available.

It could include the `Thumbnail`, when available, but this is of course not at all important.  It would make the site look nicer though.

It should include compatibility info: M versions (`MathematicaVersion` or `WolframVersion`) and maybe platforms (`SystemID`). Paclets that have binary components need separate binaries for each platform.

Here's the info that the doc browser presents:

![image](https://user-images.githubusercontent.com/1212871/39045425-302f7df2-4493-11e8-81cb-571b43f1ce94.png)

Here's what's present in PacletInfo files:

![image](https://user-images.githubusercontent.com/1212871/39045624-a7903512-4493-11e8-946a-e789f904ce0b.png)

Compare with what's currently displayed:

![image](https://user-images.githubusercontent.com/1212871/39045643-b69fc5fe-4493-11e8-9156-15514487c834.png)

**Comment by szhorvat** [comment]
Could you make the URL clickable please? (I.e. a proper `<a href="...">`)

**Comment by b3m2a1** [comment]
@szhorvat Yeah that's all simple to do. It's on my list of things to implement, but I wasn't sure how best to handle it, e.g. when given a URL that won't properly `Hyperlink` is it best still to wrap it with a link.

**Comment by b3m2a1** [comment]
@szhorvat URL's are clickable. Added mailto: links when the creator provides an email. Not sure whether this is a good idea or not.
