### ISSUE TITLE
Update paclet: MaTeX

### ISSUE THREAD

**Issue by szhorvat** [paclets/PacletServer#30]
Name: MaTeX
URL: https://github.com/szhorvat/MaTeX/releases/download/v1.7.4/MaTeX-1.7.4.paclet

**Comment by b3m2a1** [comment]
@szhorvat is it good if I just link in the newest MaTeX release each time? I'd do that by using https://github.com/szhorvat/MaTeX/releases/latest as the URL.

**Comment by szhorvat** [comment]
Yes, that's fine.

**Comment by b3m2a1** [comment]
Done. When you update just ping this and I'll rebuild.

**Comment by szhorvat** [comment]
Thanks! It's good to mention that if a release is marked as pre-release on GitHub, it won't be in https://github.com/szhorvat/MaTeX/releases/latest  This can be good or bad, depending on the situation.
