### ISSUE TITLE
Merge in paclet: Deus

### ISSUE THREAD

**Issue by GalAster** [paclets/PacletServer#31]
[Deus-v0.5.1.zip](https://github.com/GalAster/Deus/releases/download/20180603191611-570072a/Deus-v0.5.1.zip)

**Comment by b3m2a1** [comment]
@GalAster what do you want the Author line in the paclet to be? (also in the future it'd be mildly preferable if you passed a packed .paclet file but this works too--the system will pack it anyway)

**Comment by b3m2a1** [comment]
@GalAster currently this is what is up on the server: https://paclets.github.io/PacletServer/deus.html If you want to change anything you can either submit an updated paclet or I can get to them when I have the time.
