### ISSUE TITLE
Register paclet: CompoundMatrixMethod

### ISSUE THREAD

**Issue by SPPearce** [paclets/PacletServer#37]
Name: CompoundMatrixMethod
Author: Simon Pearce <simon.pearce@manchester.ac.uk>
URL: https://github.com/SPPearce/CompoundMatrixMethod

**Comment by b3m2a1** [comment]
[Merged](https://paclets.github.io/PacletServer/compoundmatrixmethod.html). Reopen this issue when you want updates pushed if I don't have it in the paclet by then.
