### ISSUE TITLE
Register paclet: OptionsValidation

### ISSUE THREAD

**Issue by jkuczm** [paclets/PacletServer#46]
Name: OptionsValidation
Author: Jakub Kuczmarski Jakub.Kuczmarski@gmail.com
URL: github-release:jkuczm/MathematicaOptionsValidation/latest

**Comment by b3m2a1** [comment]
Merged: https://paclets.github.io/PacletServer/optionsvalidation.html

**Comment by b3m2a1** [comment]
@jkuczm do you want me to update this with the new paclet extensions?

**Comment by b3m2a1** [comment]
Each build of the server requires I click a button locally. I'd like it if that weren't the case, but I haven't thought up a workable design that doesn't involve this. This also allows me to check what people are putting on the server to an extent. 

What you can do is just ping me here and I'll get the emails and rebuild. If you expect to update the paclet more often than I build the server (once a week or so) then setting `"Update"` to `"DownloadAlways"` makes sense. If not it's a large addition to the build time.

Optimally I'd be notified every time you made a new release via some kind of webhook, but I don't really know how to do this with GitHub. If you have ideas feel free to submit them [here](https://github.com/paclets/PacletServer/issues/48).

**Comment by jkuczm** [comment]
It definitely won't be updated more often than once a week. So I'll just ping.

**Comment by b3m2a1** [comment]
@jkuczm One other thing to be aware of is that the `PublicPacletServer` package actually supports this use case. You can do things like:

```mathematica
PublicPacletServer@"RequestPacletUpdate"["OptionsValidation"]
```

and it'll submit the request automatically.

Hopefully that will minimize the difficulty involved in pushing updates.

**Comment by jkuczm** [comment]
Thank, I'll take a look at it.

**Comment by b3m2a1** [comment]
I just thought up a way to automatically check for updates without breaking the time it takes me to build the serve. You only need to ping me if you want a build sooner than my basic schedule.

**Comment by jkuczm** [comment]
Great. I won't ping you unnecessarily then.
