### ISSUE TITLE
Update Paclet: MeshTools

### ISSUE THREAD

**Issue by PintarM** [paclets/PacletServer#57]
Name: MeshTools
Author: Matevz Pintar
URL: https://github.com/c3m-labs/MeshTools/releases/download/v0.4.0/MeshTools-0.4.0.paclet

**Comment by b3m2a1** [comment]
Updated: https://paclets.github.io/PacletServer/meshtools.html#main-content

If you start publishing normal releases (instead of pre-releases) let me know and I can set the server to automatically pull your latest one.

**Comment by PintarM** [comment]
Thank you.
I am planning to further improve the package and make a normal 1.0 release in the near future.

**Comment by PintarM** [comment]
Name: MeshTools
Author: Matevz Pintar
URL: https://github.com/c3m-labs/MeshTools/releases/download/v0.5.0/MeshTools-0.5.0.paclet

**Comment by b3m2a1** [comment]
Updated

**Comment by PintarM** [comment]
I have released stable version 1.0.0 of the package.

Name: MeshTools
Author: Matevz Pintar
URL: https://github.com/c3m-labs/MeshTools/releases/download/v1.0.0/MeshTools-1.0.0.paclet
