### ISSUE TITLE
Register Paclet OBJImporter

### ISSUE THREAD

**Issue by cekdahl** [paclets/PacletServer#59]
Name: OBJImporter
Author: CE
URL: https://github.com/cekdahl/OBJImporter
Release: True

**Comment by b3m2a1** [comment]
Merged: https://paclets.github.io/PacletServer/objimporter.html

It'll auto-update to the latest release, but if you want updates sooner than my regular more-or-less Monday/Friday schedule  reopen this issue and let me know
