### ISSUE TITLE
Inappropriate context name appears in generated paclet page

### ISSUE THREAD

**Issue by szhorvat** [paclets/PacletServer#9]
See here:

https://paclets.github.io/PacletServer/matex.html#main-content

![image](https://user-images.githubusercontent.com/1212871/39272204-8e183d7c-48db-11e8-9a38-5240c82ab8e4.png)

**Comment by b3m2a1** [comment]
Thought I'd pruned this particular bug. I'll make sure to use `SymbolName` on top of setting ``Internal`$ContextMarks`` to `False`.

**Comment by b3m2a1** [comment]
Fixed and shouldn't pop up again
